apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: pujitha-namespace # replace with your namespace parameter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: ganjiprasannapujitha03/spring-boot-demo:latest
        ports:
        - containerPort: 8080
