apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: pujitha-namespace
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8080         # service port (inside cluster)
      targetPort: 8080   # pod port
      
